### ISSUE TITLE
Why is this not a backend for the PackageKit extension?

### ISSUE THREAD

**Issue by rokejulianlockhart** [cockpit-project/cockpit-ostree#302]
Why is this not merely a backend for [the PackageKit extension of Cockpit](https://cockpit-project.org/applications.html#:~:text=software%20updates%20(packagekit)%20)? Surely that would be more cohesive than a separate extension for solely this package-manager.

**Comment by martinpitt** [comment]
Because the two have nothing in common except for the name in the menu. They use different backends (PackageKit vs. rpm-ostree), have completely different functionality and UI, and were even historically developed independently. Moving them into one rpm doesn't make sense, as the only way to specify its dependencies would be `PackageKit OR rpm-ostree`.
